[package]
name = "ttytee"
version = "0.2.0"
authors = ["Salamandar <felix@piedallu.me>"]
edition = "2021"

[dependencies]
gettext-rs = { version = "0.7", features = ["gettext-system"] }
log = "0.4"
# once_cell = "1.14"
pretty_env_logger = "0.4"
